local concat = table.concat
local insert = table.insert
local sprintf = string.format
local rep = string.rep

local luanti_example_header = [[
#    This file contains a list of all available settings and their default value for luanti.conf

#    By default, all the settings are commented and not functional.
#    Uncomment settings by removing the preceding #.

#    luanti.conf is read by default from:
#    ../luanti.conf
#    ../../luanti.conf
#    Any other path can be chosen by passing the path as a parameter
#    to the program, eg. "luanti.exe --config ../luanti.conf.example".

#    Further documentation:
#    https://wiki.luanti.org/

#    Note: If you have an existing minetest.conf file, it will be automatically
#    converted to luanti.conf format when you first run the program.

]]

local group_format_template = [[
# %s = {
#    offset      = %s,
#    scale       = %s,
#    spread      = (%s, %s, %s),
#    seed        = %s,
#    octaves     = %s,
#    persistence = %s,
#    lacunarity  = %s,
#    flags       =%s
# }

]]

local function create_luanti_conf_example(settings)
	local result = { luanti_example_header }
	for _, entry in ipairs(settings) do
		if entry.type == "category" then
			if entry.level == 0 then
				insert(result, "#\n# " .. entry.name .. "\n#\n\n")
			else
				insert(result, rep("#", entry.level))
				insert(result, "# " .. entry.name .. "\n\n")
			end
		else
			local group_format = false
			if entry.noise_params and entry.values then
				if entry.type == "noise_params_2d" or entry.type == "noise_params_3d" then
					group_format = true
				end
			end
			if entry.comment ~= "" then
				for _, comment_line in ipairs(entry.comment:split("\n", true)) do
					if comment_line == "" then
						insert(result, "#\n")
					else
						insert(result, "#    " .. comment_line .. "\n")
					end
				end
			end
			if entry.type == "key" then
				local line = "See https://github.com/luanti-org/luanti/blob/master/irr/include/Keycodes.h"
				insert(result, "#    " .. line .. "\n")
			end
			insert(result, "#    type: " .. entry.type)
			if entry.min then
				insert(result, " min: " .. entry.min)
			end
			if entry.max then
				insert(result, " max: " .. entry.max)
			end
			if entry.values and entry.noise_params == nil then
				insert(result, " values: " .. concat(entry.values, ", "))
			end
			if entry.possible then
				insert(result, " possible values: " .. concat(entry.possible, ", "))
			end
			insert(result, "\n")
			if group_format == true then
				local flags = entry.values[10]
				if flags ~= "" then
					flags = " "..flags
				end
				insert(result, sprintf(group_format_template, entry.name, entry.values[1],
						entry.values[2], entry.values[3], entry.values[4], entry.values[5],
						entry.values[6], entry.values[7], entry.values[8], entry.values[9],
						flags))
			else
				local append
				if entry.default ~= "" then
					append = " " .. entry.default
				end
				insert(result, sprintf("# %s =%s\n\n", entry.name, append or ""))
			end
		end
	end
	return concat(result)
end

local translation_file_header = [[
// This file is automatically generated
// It contains a bunch of fake gettext calls, to tell xgettext about the strings in config files
// To update it, refer to the bottom of builtin/mainmenu/dlg_settings_advanced.lua

fake_function() {]]

local function create_translation_file(settings)
	local result = { translation_file_header }
	for _, entry in ipairs(settings) do
		if entry.type == "category" then
			insert(result, sprintf("\tgettext(%q);", entry.name))
		else
			if entry.readable_name then
				insert(result, sprintf("\tgettext(%q);", entry.readable_name))
			end
			if entry.comment ~= "" then
				local comment_escaped = entry.comment:gsub("\n", "\\n")
				comment_escaped = comment_escaped:gsub("\"", "\\\"")
				insert(result, "\tgettext(\"" .. comment_escaped .. "\");")
			end
		end
	end
	insert(result, "}\n")
	return concat(result, "\n")
end

-- Check if minetest.conf exists and convert it to luanti.conf if needed
local function convert_minetest_to_luanti()
	local minetest_conf = io.open("minetest.conf", "r")
	if minetest_conf then
		local content = minetest_conf:read("*all")
		minetest_conf:close()
		
		-- Only convert if luanti.conf doesn't exist yet
		local luanti_conf = io.open("luanti.conf", "r")
		if not luanti_conf then
			luanti_conf = io.open("luanti.conf", "w")
			if luanti_conf then
				luanti_conf:write(content)
				luanti_conf:close()
				print("Converted minetest.conf to luanti.conf")
				-- Delete the original minetest.conf file
				os.remove("minetest.conf")
				print("Deleted original minetest.conf file")
			end
		else
			luanti_conf:close()
		end
	end
end

-- Generate example config file
local file = assert(io.open("luanti.conf.example", "w"))
file:write(create_luanti_conf_example(settingtypes.parse_config_file(true, false)))
file:close()

-- Check for and convert minetest.conf if it exists
convert_minetest_to_luanti()

file = assert(io.open("src/settings_translation_file.cpp", "w"))
file:write(create_translation_file(settingtypes.parse_config_file(false, false)))
file:close()
